version: '2'

services:
    db:
        image: mariadb:10
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: codeadvent2016
            MYSQL_DATABASE: codeadvent2016
            MYSQL_USER: codeadvent2016
            MYSQL_PASSWORD: codeadvent2016

    codeadventapp:
        depends_on:
            - db
        image: registry.gitlab.cafe/may/app:latest
        volumes:
            - codeadvent_data:/var/www/html/webroot/data
        ports:
            - "8081:80"
        restart: always
        environment:
            MYSQL_HOST: db
            MYSQL_USER: codeadvent2016
            MYSQL_PASS: codeadvent2016
            MYSQL_DB_NAME: codeadvent2016
volumes:
    db_data:
    codeadvent_data:
